replicaCount: 1

image:
  repository: davemcmahon/triageai
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

ezua:
  virtualService:
    endpoint: "healthcare-ai.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"

models:
  medreason:
    url: "[MLIS ENDPOINT GOES HERE]/v1/completions"
    token: "[MLIS TOKEN GOES HERE]"
  
  whisper:
    url: "[MLIS ENDPOINT GOES HERE]/v1/audio/transcriptions"
    token: "[MLIS TOKEN GOES HERE]"
  
  nllb:
    url: "[MLIS ENDPOINT GOES HERE]/v1/models/nllb-translator:predict"
    token: "[MLIS TOKEN GOES HERE]"
  
  medgemma:
    url: "[MLIS ENDPOINT GOES HERE]"
    token: "[MLIS TOKEN GOES HERE]"

# Database Configuration
database:
  host: "ezmysql.ezmeral.demo.local"
  user: "demo_user"
  password: "Hpepoc@123"
  name: "triageai"